#!/usr/bin/env bash
# Expand only the macros defined in certain/utils/light_list.h.
#
# gcc/clang -E expands *every* macro. Feeding light_list_test.cc directly
# therefore dumps googletest. The recipe is:
#   1. comment out all #include lines (so gtest / STL stay as tokens)
#   2. inject LIGHTLIST* macros with -imacros (defines them, inserts no text)
#   3. run the preprocessor
#
# Usage:
#   certain/tools/expand_light_list.sh
#   certain/tools/expand_light_list.sh certain/utils/light_list_test.cc
#   certain/tools/expand_light_list.sh -o /tmp/out.cc certain/utils/lru_table.h

set -euo pipefail

usage() {
  cat <<'EOF'
usage: expand_light_list.sh [-o outfile] [source...]

Default sources (utils/ call sites):
  certain/utils/light_list_test.cc
  certain/utils/array_timer.h
  certain/utils/lru_table.h

Default outfile:
  certain/tools/light_list_expanded.cc
EOF
}

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
CERTAIN_DIR=$(cd "$SCRIPT_DIR/.." && pwd)
LIGHT_LIST_H=$CERTAIN_DIR/utils/light_list.h
OUT=$SCRIPT_DIR/light_list_expanded.cc
SOURCES=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    -o)
      OUT=$2
      shift 2
      ;;
    --)
      shift
      SOURCES+=("$@")
      break
      ;;
    -*)
      echo "unknown flag: $1" >&2
      usage >&2
      exit 2
      ;;
    *)
      SOURCES+=("$1")
      shift
      ;;
  esac
done

if [[ ${#SOURCES[@]} -eq 0 ]]; then
  SOURCES=(
    "$CERTAIN_DIR/utils/light_list_test.cc"
    "$CERTAIN_DIR/utils/array_timer.h"
    "$CERTAIN_DIR/utils/lru_table.h"
  )
fi

CXX=${CXX:-}
if [[ -z "$CXX" ]]; then
  if command -v clang++ >/dev/null 2>&1; then
    CXX=clang++
  else
    CXX=g++
  fi
fi

comment_includes() {
  # Keep the source text; only drop includes / pragma so -E does not
  # pull headers in or warn about #pragma once in a main file.
  sed -E \
    -e 's|^[[:space:]]*#[[:space:]]*include|// include|' \
    -e 's|^[[:space:]]*#[[:space:]]*pragma once|// pragma once|' \
    "$1"
}

expand_one() {
  local src=$1
  local tmp
  tmp=$(mktemp)
  comment_includes "$src" >"$tmp"
  # -imacros: parse light_list.h for #define, discard its output.
  # -P: no linemarkers. -C: keep comments from the *source* file.
  "$CXX" -std=c++11 -E -P -C -x c++ \
    -imacros "$LIGHT_LIST_H" \
    -I "$CERTAIN_DIR" \
    "$tmp"
  rm -f "$tmp"
}

{
  cat <<'EOF'
// Generated by certain/tools/expand_light_list.sh — do not compile.
// Only LIGHTLIST* / ENTRY_IN_LIGHTLIST from utils/light_list.h were expanded.
// Other tokens (TEST, ASSERT_*, std::...) are unchanged on purpose.
//
// Recipe (same as this script):
//   1. comment out every #include
//   2. clang++ -std=c++11 -E -P -C -x c++ \
//        -imacros certain/utils/light_list.h -I certain  source.cc
// -imacros loads #define lines and discards the header text, so only those
// macros are substituted.

EOF

  for src in "${SOURCES[@]}"; do
    if [[ ! -f "$src" ]]; then
      echo "missing source: $src" >&2
      exit 1
    fi
    rel=${src#"$CERTAIN_DIR/"}
    echo
    echo "// ============================================================================="
    echo "// $rel"
    echo "// ============================================================================="
    echo
    expand_one "$src"
    echo
  done
} >"$OUT"

# -E collapses multi-line macros onto one line. Split do { ... } while (0)
# so INSERT/REMOVE are readable. if/else without braces stay valid C.
if command -v python3 >/dev/null 2>&1; then
  python3 - "$OUT" <<'PY'
import re
import sys

path = sys.argv[1]
text = open(path).read()


def expand_do(match):
    body = match.group(1)
    stmts = [s.strip() for s in body.split(";") if s.strip()]
    inner = "".join("    %s;\n" % s for s in stmts)
    return "do {\n" + inner + "} while (0)"


text = re.sub(r"do \{ (.*?) \} while \(0\)", expand_do, text, flags=re.S)

# Re-indent each do-while from the column of its "do {".
lines = text.splitlines()
out = []
i = 0
while i < len(lines):
    raw = lines[i]
    stripped = raw.strip()
    if stripped == "do {":
        indent = re.match(r"^(\s*)", raw).group(1)
        out.append(indent + "do {")
        i += 1
        while i < len(lines) and not lines[i].lstrip().startswith("} while"):
            out.append(indent + "  " + lines[i].strip())
            i += 1
        if i < len(lines):
            out.append(indent + lines[i].lstrip())
            i += 1
        continue
    out.append(raw)
    i += 1

open(path, "w").write("\n".join(out) + "\n")
PY
fi

echo "wrote $OUT" >&2
