// Generated by certain/tools/expand_light_list.sh — do not compile.
// Only LIGHTLIST* / ENTRY_IN_LIGHTLIST from utils/light_list.h were expanded.
// Other tokens (TEST, ASSERT_*, std::...) are unchanged on purpose.
//
// Recipe (same as this script):
//   1. comment out every #include
//   2. clang++ -std=c++11 -E -P -C -x c++ \
//        -imacros certain/utils/light_list.h -I certain  source.cc
// -imacros loads #define lines and discards the header text, so only those
// macros are substituted.


// =============================================================================
// utils/light_list_test.cc
// =============================================================================

// include "utils/light_list.h"
// include "gtest/gtest.h"
struct Foo {
  int bar;
  struct { Foo* next; Foo* prev; } test_list_entry;
  Foo() = delete;
  Foo(int _bar) {
    bar = _bar;
    do {
      (this)->test_list_entry.next = NULL;
      (this)->test_list_entry.prev = NULL;
    } while (0);
  }
};
TEST(LightListTest, Basic) {
  struct { Foo* first; Foo* last; } test_list;
  do {
    *(void**)&(&test_list)->first = (void*)(&test_list);
    *(void**)&(&test_list)->last = (void*)(&test_list);
  } while (0);
  Foo e1(1);
  Foo e2(2);
  Foo e3(3);
  // Insert e1 and than remove it.
  ASSERT_FALSE(((&e1)->test_list_entry.next != NULL && (&e1)->test_list_entry.prev != NULL));
  do {
    (&e1)->test_list_entry.next = (&test_list)->first;
    *(void**)&(&e1)->test_list_entry.prev = (void*)(&test_list);
    if ((void*)(&test_list)->last == (void*)(&test_list)) (&test_list)->last = (&e1);
    else (&test_list)->first->test_list_entry.prev = (&e1);
    (&test_list)->first = (&e1);
  } while (0);
  ASSERT_TRUE(((&e1)->test_list_entry.next != NULL && (&e1)->test_list_entry.prev != NULL));
  do {
    if ((void*)(&e1)->test_list_entry.next == (void*)(&test_list)) (&test_list)->last = (&e1)->test_list_entry.prev;
    else (&e1)->test_list_entry.next->test_list_entry.prev = (&e1)->test_list_entry.prev;
    if ((void*)(&e1)->test_list_entry.prev == (void*)(&test_list)) (&test_list)->first = (&e1)->test_list_entry.next;
    else (&e1)->test_list_entry.prev->test_list_entry.next = (&e1)->test_list_entry.next;
    (&e1)->test_list_entry.next = NULL;
    (&e1)->test_list_entry.prev = NULL;
  } while (0);
  ASSERT_FALSE(((&e1)->test_list_entry.next != NULL && (&e1)->test_list_entry.prev != NULL));
  do {
    (&e1)->test_list_entry.next = (&test_list)->first;
    *(void**)&(&e1)->test_list_entry.prev = (void*)(&test_list);
    if ((void*)(&test_list)->last == (void*)(&test_list)) (&test_list)->last = (&e1);
    else (&test_list)->first->test_list_entry.prev = (&e1);
    (&test_list)->first = (&e1);
  } while (0);
  do {
    (&e2)->test_list_entry.next = (&test_list)->first;
    *(void**)&(&e2)->test_list_entry.prev = (void*)(&test_list);
    if ((void*)(&test_list)->last == (void*)(&test_list)) (&test_list)->last = (&e2);
    else (&test_list)->first->test_list_entry.prev = (&e2);
    (&test_list)->first = (&e2);
  } while (0);
  do {
    (&e3)->test_list_entry.next = (&test_list)->first;
    *(void**)&(&e3)->test_list_entry.prev = (void*)(&test_list);
    if ((void*)(&test_list)->last == (void*)(&test_list)) (&test_list)->last = (&e3);
    else (&test_list)->first->test_list_entry.prev = (&e3);
    (&test_list)->first = (&e3);
  } while (0);
  ASSERT_FALSE(((void*)(&test_list)->first == (void*)(&test_list)));
  // Check e3.
  ASSERT_EQ(((&test_list)->first)->bar, 3);
  ASSERT_TRUE(((&e3)->test_list_entry.next != NULL && (&e3)->test_list_entry.prev != NULL));
  do {
    if ((void*)(&e3)->test_list_entry.next == (void*)(&test_list)) (&test_list)->last = (&e3)->test_list_entry.prev;
    else (&e3)->test_list_entry.next->test_list_entry.prev = (&e3)->test_list_entry.prev;
    if ((void*)(&e3)->test_list_entry.prev == (void*)(&test_list)) (&test_list)->first = (&e3)->test_list_entry.next;
    else (&e3)->test_list_entry.prev->test_list_entry.next = (&e3)->test_list_entry.next;
    (&e3)->test_list_entry.next = NULL;
    (&e3)->test_list_entry.prev = NULL;
  } while (0);
  ASSERT_FALSE(((&e3)->test_list_entry.next != NULL && (&e3)->test_list_entry.prev != NULL));
  // Check e2.
  ASSERT_EQ(((&test_list)->first)->bar, 2);
  ASSERT_TRUE(((&e2)->test_list_entry.next != NULL && (&e2)->test_list_entry.prev != NULL));
  do {
    if ((void*)(&e2)->test_list_entry.next == (void*)(&test_list)) (&test_list)->last = (&e2)->test_list_entry.prev;
    else (&e2)->test_list_entry.next->test_list_entry.prev = (&e2)->test_list_entry.prev;
    if ((void*)(&e2)->test_list_entry.prev == (void*)(&test_list)) (&test_list)->first = (&e2)->test_list_entry.next;
    else (&e2)->test_list_entry.prev->test_list_entry.next = (&e2)->test_list_entry.next;
    (&e2)->test_list_entry.next = NULL;
    (&e2)->test_list_entry.prev = NULL;
  } while (0);
  ASSERT_FALSE(((&e2)->test_list_entry.next != NULL && (&e2)->test_list_entry.prev != NULL));
  // Check e1.
  ASSERT_EQ(((&test_list)->first)->bar, 1);
  ASSERT_TRUE(((&e1)->test_list_entry.next != NULL && (&e1)->test_list_entry.prev != NULL));
  do {
    if ((void*)(&e1)->test_list_entry.next == (void*)(&test_list)) (&test_list)->last = (&e1)->test_list_entry.prev;
    else (&e1)->test_list_entry.next->test_list_entry.prev = (&e1)->test_list_entry.prev;
    if ((void*)(&e1)->test_list_entry.prev == (void*)(&test_list)) (&test_list)->first = (&e1)->test_list_entry.next;
    else (&e1)->test_list_entry.prev->test_list_entry.next = (&e1)->test_list_entry.next;
    (&e1)->test_list_entry.next = NULL;
    (&e1)->test_list_entry.prev = NULL;
  } while (0);
  ASSERT_FALSE(((&e1)->test_list_entry.next != NULL && (&e1)->test_list_entry.prev != NULL));
  ASSERT_TRUE(((void*)(&test_list)->first == (void*)(&test_list)));
}
int main(int argc, char** argv) {
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}


// =============================================================================
// utils/array_timer.h
// =============================================================================

// pragma once
// include "utils/light_list.h"
// include "utils/time.h"
namespace certain {
template <typename T>
class ArrayTimer {
 public:
  struct EltEntry {
    uint32_t index;
    struct { T* next; T* prev; } timer_list_entry;
    void Init() {
      index = 0; // For Remove method.
      do {
        (this)->timer_list_entry.next = NULL;
        (this)->timer_list_entry.prev = NULL;
      } while (0);
    }
    EltEntry() { Init(); }
  };
 private:
  const uint32_t kReadyListIndex = uint32_t(-1);
  uint32_t timer_cnt_;
  uint32_t ready_cnt_;
  uint32_t max_timeout_msec_;
  uint32_t curr_index_;
  uint64_t curr_time_msec_;
  typedef struct { T* first; T* last; } TimerList;
  TimerList* timer_list_;
  TimerList* ready_list_;
  // Return how many timer moved.
  uint32_t MoveTimerToReadyListByIndex(uint32_t index) {
    assert(index <= max_timeout_msec_);
    TimerList* curr_list = &timer_list_[index];
    uint32_t moved_cnt = 0;
    while (!((void*)(curr_list)->first == (void*)(curr_list))) {
      T* last = ((curr_list)->last);
      do {
        if ((void*)(last)->timer_entry.timer_list_entry.next == (void*)(curr_list)) (curr_list)->last = (last)->timer_entry.timer_list_entry.prev;
        else (last)->timer_entry.timer_list_entry.next->timer_entry.timer_list_entry.prev = (last)->timer_entry.timer_list_entry.prev;
        if ((void*)(last)->timer_entry.timer_list_entry.prev == (void*)(curr_list)) (curr_list)->first = (last)->timer_entry.timer_list_entry.next;
        else (last)->timer_entry.timer_list_entry.prev->timer_entry.timer_list_entry.next = (last)->timer_entry.timer_list_entry.next;
        (last)->timer_entry.timer_list_entry.next = NULL;
        (last)->timer_entry.timer_list_entry.prev = NULL;
      } while (0);
      assert(last->timer_entry.index == index);
      last->timer_entry.index = kReadyListIndex;
      do {
        (last)->timer_entry.timer_list_entry.next = (ready_list_)->first;
        *(void**)&(last)->timer_entry.timer_list_entry.prev = (void*)(ready_list_);
        if ((void*)(ready_list_)->last == (void*)(ready_list_)) (ready_list_)->last = (last);
        else (ready_list_)->first->timer_entry.timer_list_entry.prev = (last);
        (ready_list_)->first = (last);
      } while (0);
      moved_cnt++;
    }
    return moved_cnt;
  }
  // Move add all timers before curr_time_msec to ready_list_, then update
  // curr_time_msec_, curr_index_, timer_cnt_ and ready_cnt_.
  void MoveTimerToReadyList(uint64_t curr_time_msec) {
    // Fix curr_time_msec if it's not monotonnous.
    if (curr_time_msec < curr_time_msec_) {
      curr_time_msec = curr_time_msec_;
    }
    uint64_t range = curr_time_msec - curr_time_msec_;
    if (range > max_timeout_msec_) {
      range = max_timeout_msec_;
    }
    uint32_t index = curr_index_;
    uint32_t moved_cnt = 0;
    for (uint32_t i = 0; i <= range; ++i) {
      index = i + curr_index_;
      // timer_list_ array is cyclic reused.
      if (index >= max_timeout_msec_ + 1) {
        index -= max_timeout_msec_ + 1;
      }
      moved_cnt += MoveTimerToReadyListByIndex(index);
    }
    ready_cnt_ += moved_cnt;
    timer_cnt_ -= moved_cnt;
    curr_time_msec_ = curr_time_msec;
    curr_index_ = index;
  }
 public:
  // Support timer alarms in [0, max_timeout_msec].
  ArrayTimer(uint32_t max_timeout_msec) {
    timer_cnt_ = 0;
    ready_cnt_ = 0;
    max_timeout_msec_ = max_timeout_msec;
    timer_list_ = (TimerList*)calloc(max_timeout_msec_ + 1, sizeof(TimerList));
    assert(timer_list_ != NULL);
    for (uint32_t i = 0; i <= max_timeout_msec_; ++i) {
      do {
        *(void**)&(&timer_list_[i])->first = (void*)(&timer_list_[i]);
        *(void**)&(&timer_list_[i])->last = (void*)(&timer_list_[i]);
      } while (0);
    }
    ready_list_ = (TimerList*)calloc(1, sizeof(TimerList));
    do {
      *(void**)&(ready_list_)->first = (void*)(ready_list_);
      *(void**)&(ready_list_)->last = (void*)(ready_list_);
    } while (0);
    curr_index_ = 0;
    curr_time_msec_ = GetTimeByMsec();
  }
  ~ArrayTimer() {
    free(ready_list_);
    free(timer_list_);
  }
  uint32_t Size() { return timer_cnt_ + ready_cnt_; }
  bool Add(T* elt, uint32_t timeout_msec) {
    assert(timeout_msec <= max_timeout_msec_);
    if (Exist(elt)) {
      return false;
    }
    uint64_t msec = GetTimeByMsec();
    MoveTimerToReadyList(msec);
    uint32_t index = curr_index_ + timeout_msec;
    if (index >= max_timeout_msec_ + 1) {
      index -= (max_timeout_msec_ + 1);
    }
    elt->timer_entry.index = index;
    do {
      (elt)->timer_entry.timer_list_entry.next = (&timer_list_[index])->first;
      *(void**)&(elt)->timer_entry.timer_list_entry.prev = (void*)(&timer_list_[index]);
      if ((void*)(&timer_list_[index])->last == (void*)(&timer_list_[index])) (&timer_list_[index])->last = (elt);
      else (&timer_list_[index])->first->timer_entry.timer_list_entry.prev = (elt);
      (&timer_list_[index])->first = (elt);
    } while (0);
    timer_cnt_++;
    return true;
  }
  bool Remove(T* elt) {
    if (!Exist(elt)) {
      assert(elt->timer_entry.index == 0);
      return false;
    }
    TimerList* timer_list = ready_list_;
    if (elt->timer_entry.index != kReadyListIndex) {
      timer_list = &timer_list_[elt->timer_entry.index];
      timer_cnt_--;
    } else {
      ready_cnt_--;
    }
    do {
      if ((void*)(elt)->timer_entry.timer_list_entry.next == (void*)(timer_list)) (timer_list)->last = (elt)->timer_entry.timer_list_entry.prev;
      else (elt)->timer_entry.timer_list_entry.next->timer_entry.timer_list_entry.prev = (elt)->timer_entry.timer_list_entry.prev;
      if ((void*)(elt)->timer_entry.timer_list_entry.prev == (void*)(timer_list)) (timer_list)->first = (elt)->timer_entry.timer_list_entry.next;
      else (elt)->timer_entry.timer_list_entry.prev->timer_entry.timer_list_entry.next = (elt)->timer_entry.timer_list_entry.next;
      (elt)->timer_entry.timer_list_entry.next = NULL;
      (elt)->timer_entry.timer_list_entry.prev = NULL;
    } while (0);
    elt->timer_entry.Init();
    return true;
  }
  T* TakeTimerElt() {
    if (ready_cnt_ == 0) {
      MoveTimerToReadyList(GetTimeByMsec());
      if (ready_cnt_ == 0) {
        return NULL;
      }
    }
    T* elt = ((ready_list_)->last);
    bool bRemoved = Remove(elt);
    assert(bRemoved);
    return elt;
  }
  bool Exist(T* elt) {
    if (((elt)->timer_entry.timer_list_entry.next != NULL && (elt)->timer_entry.timer_list_entry.prev != NULL)) {
      return true;
    } else {
      assert(elt->timer_entry.index == 0);
      return false;
    }
  }
};
} // namespace certain


// =============================================================================
// utils/lru_table.h
// =============================================================================

// pragma once
// include "utils/header.h"
// include "utils/light_list.h"
namespace certain {
template <typename K, typename V>
class LruTable {
 private:
  struct LruElt;
  typedef std::unordered_map<K, LruElt> HashTable;
  typedef typename HashTable::iterator HashTableIter;
  struct LruElt {
    K key;
    V value;
    struct { LruElt* next; LruElt* prev; } list_entry;
    LruElt() {}
    LruElt(const K& _key, const V& _value) {
      key = _key;
      value = _value;
      do {
        (this)->list_entry.next = NULL;
        (this)->list_entry.prev = NULL;
      } while (0);
    }
  };
  uint64_t max_size_;
  bool auto_eliminate_;
  HashTable hash_table_;
  struct { LruElt* first; LruElt* last; } lru_list_;
 public:
  LruTable(uint64_t max_size = 1024, bool auto_eliminate = false) {
    max_size_ = max_size;
    auto_eliminate_ = auto_eliminate;
    hash_table_.reserve(max_size_);
    do {
      *(void**)&(&lru_list_)->first = (void*)(&lru_list_);
      *(void**)&(&lru_list_)->last = (void*)(&lru_list_);
    } while (0);
  }
  virtual ~LruTable() {}
  uint64_t Size() { return hash_table_.size(); }
  bool Add(const K& key, const V& value) {
    bool ok = false;
    LruElt* elt = NULL;
    HashTableIter iter = hash_table_.find(key);
    if (iter != hash_table_.end()) {
      do {
        if ((void*)(&iter->second)->list_entry.next == (void*)(&lru_list_)) (&lru_list_)->last = (&iter->second)->list_entry.prev;
        else (&iter->second)->list_entry.next->list_entry.prev = (&iter->second)->list_entry.prev;
        if ((void*)(&iter->second)->list_entry.prev == (void*)(&lru_list_)) (&lru_list_)->first = (&iter->second)->list_entry.next;
        else (&iter->second)->list_entry.prev->list_entry.next = (&iter->second)->list_entry.next;
        (&iter->second)->list_entry.next = NULL;
        (&iter->second)->list_entry.prev = NULL;
      } while (0);
      iter->second = LruElt(key, value);
      elt = &(iter->second);
    } else {
      elt = &(hash_table_[key] = LruElt(key, value));
      ok = true;
    }
    do {
      (elt)->list_entry.next = (&lru_list_)->first;
      *(void**)&(elt)->list_entry.prev = (void*)(&lru_list_);
      if ((void*)(&lru_list_)->last == (void*)(&lru_list_)) (&lru_list_)->last = (elt);
      else (&lru_list_)->first->list_entry.prev = (elt);
      (&lru_list_)->first = (elt);
    } while (0);
    if (auto_eliminate_ && hash_table_.size() > max_size_) {
      bool removed = RemoveOldest();
      assert(removed);
    }
    return ok;
  }
  bool Remove(const K& key) {
    HashTableIter iter = hash_table_.find(key);
    if (iter == hash_table_.end()) {
      return false;
    }
    do {
      if ((void*)(&iter->second)->list_entry.next == (void*)(&lru_list_)) (&lru_list_)->last = (&iter->second)->list_entry.prev;
      else (&iter->second)->list_entry.next->list_entry.prev = (&iter->second)->list_entry.prev;
      if ((void*)(&iter->second)->list_entry.prev == (void*)(&lru_list_)) (&lru_list_)->first = (&iter->second)->list_entry.next;
      else (&iter->second)->list_entry.prev->list_entry.next = (&iter->second)->list_entry.next;
      (&iter->second)->list_entry.next = NULL;
      (&iter->second)->list_entry.prev = NULL;
    } while (0);
    hash_table_.erase(iter);
    return true;
  }
  bool RemoveOldest() {
    if (hash_table_.size() == 0) {
      return false;
    }
    LruElt* elt = ((&lru_list_)->last);
    bool removed = Remove(elt->key);
    assert(removed);
    return true;
  }
  bool PeekOldest(K& key, V& value) {
    if (hash_table_.size() == 0) {
      return false;
    }
    LruElt* elt = ((&lru_list_)->last);
    key = elt->key;
    value = elt->value;
    return true;
  }
  bool Find(const K& key, V& value) {
    HashTableIter iter = hash_table_.find(key);
    if (iter == hash_table_.end()) {
      return false;
    }
    value = iter->second.value;
    return true;
  }
  bool Find(const K& key) { return hash_table_.find(key) != hash_table_.end(); }
  bool Refresh(const K& key, bool newest = true) {
    HashTableIter iter = hash_table_.find(key);
    if (iter == hash_table_.end()) {
      return false;
    }
    do {
      if ((void*)(&iter->second)->list_entry.next == (void*)(&lru_list_)) (&lru_list_)->last = (&iter->second)->list_entry.prev;
      else (&iter->second)->list_entry.next->list_entry.prev = (&iter->second)->list_entry.prev;
      if ((void*)(&iter->second)->list_entry.prev == (void*)(&lru_list_)) (&lru_list_)->first = (&iter->second)->list_entry.next;
      else (&iter->second)->list_entry.prev->list_entry.next = (&iter->second)->list_entry.next;
      (&iter->second)->list_entry.next = NULL;
      (&iter->second)->list_entry.prev = NULL;
    } while (0);
    LruElt* elt = &(iter->second);
    if (newest) {
      do {
        (elt)->list_entry.next = (&lru_list_)->first;
        *(void**)&(elt)->list_entry.prev = (void*)(&lru_list_);
        if ((void*)(&lru_list_)->last == (void*)(&lru_list_)) (&lru_list_)->last = (elt);
        else (&lru_list_)->first->list_entry.prev = (elt);
        (&lru_list_)->first = (elt);
      } while (0);
    } else {
      do {
        *(void**)&(elt)->list_entry.next = (void*)(&lru_list_);
        (elt)->list_entry.prev = (&lru_list_)->last;
        if ((void*)(&lru_list_)->first == (void*)(&lru_list_)) (&lru_list_)->first = (elt);
        else (&lru_list_)->last->list_entry.next = (elt);
        (&lru_list_)->last = (elt);
      } while (0);
    }
    return true;
  }
  bool OverLoad() { return hash_table_.size() > max_size_; }
};
} // namespace certain

